---
development:
  MSG_KEY: 'DX2HiPHhgh6aMmq09iWzeWoiUGwdZkiMCyBiJ9lOv6U='
  SESSION_SECRET: '/pg5GeAz57XF7EUR7J8YTVpyDFxN3fZx1MT6Gv5e6Ei21O5aoPRqt8WclmC1E6mH7eVvwqp7kX2i7Hge8jD8VQ=='
  REDIS_URL: <provision Redis instance and provide URL>

test:
  MSG_KEY: 'V5zXEYuJdH3KrRWkVfGQ9UXuXGjbWTRGOTct3ZIH4EU='
  SESSION_SECRET: 'NM/iN7AO6HD+ubbYBdHCor9/uwuuDs8IVoBW/wnVk1D/YY0dyiq7G4IHllQwM5mubiiFEcpF/byIYU2FQBzyPw=='
  REDIS_URL: <provision Redis instance and provide URL>

production:
  MSG_KEY: 'IkopCNg4l4mxRg/YiPnZjLi0dwDYeQLJP+IhC0m4dCE='
  SESSION_SECRET: 'V41Sh2tyLc1k+rFegHdUSEgpgqLSOuXxlJ/FVj5skKRHsI0TZUcu3lq0EtxT7ye6B0KZ9a8wn+En6r4lbbqlug=='
  REDIS_URL: <provision Redis instance and provide URL> 
